---
title: Item Anatomy
---
graph LR

%% Structure
	subgraph structure["`**Structure**`"]
	direction LR
		stType01["`**What 1**`"] --> stType02
		stType02["`**What 2**`"] --> stType03
		stType03["`**What 3**`"] --> stTrait00 & stTrait01
		stTrait00["`**How**`"] --> stAnatomy01
		stTrait01["`**Where**`"] --> stAnatomy01
		stAnatomy01["`Locations`"]
	end
	
	%% Stucture Flow

%% Typology
	subgraph type01Apparel["`Apparel`"]
		type02Ornament["`Ornament`"]
		
		type02Ornament --> type03Brooch
		type02Ornament --> type03Pendant

		type03Brooch["`Brooch`"]
		type03Pendant["`Pendant`"]
	end

	subgraph type01Container["`Container`"]
		type02Store["`Storage`"]
		type02Vessel["`Vessel`"]

		type02Store --> type03Jar
		type02Store --> type03Jug
		type02Store --> type03Pot
		type02Store --> type03Urn
		type02Store --> type03Vase
		type02Vessel --> type03Cup
		type02Vessel --> type03Jug
		type02Vessel --> type03Mug

		type03Cup["`Cup`"]
		type03Jar["`Jar`"]
		type03Jug["`Jug`"]
		type03Mug["`Mug`"]
		type03Pot["`Pot`"]
		type03Urn["`Urn`"]
		type03Vase["`Vase`"]
	end

	subgraph type01Implement["`Implement`"]
		type02Tool["`Tool`"]
		type02Weapon["`Weapon`"]

		type02Tool --> type03Axe
		type02Tool --> type03Shovel
		type02Weapon --> type03Axe
		type02Weapon --> type03Dagger
		type02Weapon --> type03Spear
		type02Weapon --> type03Sword

		type03Axe["`Axe`"]
		type03Dagger["`Dagger`"]
		type03Shovel["`Shovel`"]
		type03Spear["`Spear`"]
		type03Sword["`Sword`"]
	end

%% Traits
	%% Trait Nodes
		%% trait00: Orientation
		trait00Face["`**How**
		Face`"]
		trait00Hang["`**How**
		Hang`"]
		trait00Hold["`**How**
		Hold`"]
		trait00Stand["`**How**
		Stand`"]
		trait00Wield["`**How**
		Wield`"]

		%% trait01: Portability
		trait01Free["`**Where**
		Free`"]
		trait01Held["`**Where**
		Handheld`"]
		trait01Worn["`**Where**
		Worn`"]

	%% Trait Flow
		%% type03 --> Trait
			type03Axe --> trait00Wield
			type03Axe --> trait01Held
			type03Brooch --> trait00Face
			type03Brooch --> trait01Worn
			type03Cup --> trait00Hold & trait00Stand
			type03Cup --> trait01Held
			type03Dagger --> trait00Wield
			type03Dagger --> trait01Held
			type03Jar --> trait00Stand
			type03Jar --> trait01Free
			type03Jug --> trait00Hold & trait00Stand
			type03Jug --> trait01Free & trait01Held
			type03Mug --> trait00Hold & trait00Stand
			type03Mug --> trait01Held
			type03Pendant --> trait00Face & trait00Hang
			type03Pendant --> trait01Worn
			type03Pot --> trait00Stand
			type03Pot --> trait01Free
			type03Shovel --> trait00Wield
			type03Shovel --> trait01Held
			type03Spear --> trait00Wield
			type03Spear --> trait01Held
			type03Sword --> trait00Wield
			type03Sword --> trait01Held
			type03Urn --> trait00Stand
			type03Urn --> trait01Free
			type03Vase --> trait00Stand
			type03Vase --> trait01Free

%% Anatomy
	%% Anatomy Nodes
		%% subgraph anat1["`Locations`"]
			%% subgraph xxx["`xxx`"]
			%% end
		%% end


		%% Anatomy Category
		%% Anatomy Part

	%% Anatomy Flow
